---
title: "Regenerate figures for the GMEA paper"
author: "The GMEA team"
date: "`r Sys.Date()`"
output:
  html_document:
  toc: true
theme: cosmo
---

## Introduction

Here we evaluate the performance of different FCS methods for Infinium methylation analysis.

```{bash,pull}

git pull

```

# Workflow

## Simulation: Figure 1 and 2

```{r,fig12}

rmarkdown::render("GSE158422.Rmd")
rmarkdown::render("GSE158422_simulate020.Rmd")
rmarkdown::render("GSE158422_simulate050.Rmd")
rmarkdown::render("GSE158422_simulate100.Rmd")
rmarkdown::render("GSE158422_simulate_summary.Rmd")

```

## Sensitivity: Figure 3 and 4


```{r,fig34}

rmarkdown::render("GSE158422_sensitivity.Rmd")

```

## Integration with RNA: Figure 5

```{r,fig5}

rmarkdown::render("GSE158422_rna_int.Rmd")

```

## Aging study

```{r,fig6}

rmarkdown::render("aging_example.Rmd")

```

## IVF example

```{r,fig7}

rmarkdown::render("ART_estill2016.Rmd")
rmarkdown::render("ART_novakovic.Rmd")
rmarkdown::render("art_example.Rmd")

```

# Session information

```{r,session}

sessionInfo()

```
